version: "2"
linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - errchkjson
    - errname
    - exhaustive
    - goconst
    - gocritic
    - godot
    - gosec
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  settings:
    govet:
      enable:
        - assign
        - copylocks
        - deepequalerrors
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - stdmethods
        - unmarshal
      disable:
        - printf
    revive:
      severity: warning
      rules:
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: cognitive-complexity
          arguments:
            - 20
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: cyclomatic
          arguments:
            - 20
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: get-return
        - name: identical-branches
          severity: error
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: import-shadowing
        - name: line-length-limit
          arguments:
            - 100
          severity: error
        - name: modifies-parameter
        - name: nested-structs
        - name: package-comments
        - name: range
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
          severity: error
        - name: struct-tag
        - name: superfluous-else
        - name: var-naming
          arguments:
            - - ID
        - name: unconditional-recursion
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: useless-break
        - name: waitgroup-by-value
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: parameter 'ctx' seems to be unused, consider removing
      - path: _test\.go
        text: line-length-limit
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: major
  rules:
    - linters:
        - goimports
        - thelper
      severity: info
    - linters:
        - dupl
        - goconst
        - tparallel
        - unconvert
        - unparam
      severity: minor
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
