// Protobuf interface of the neon service.
//
// Copyright (c) 2022 Wibowo Arindrarto <contact@arindrarto.dev>
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: neon.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FeedUrl       string                 `protobuf:"bytes,3,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	SiteUrl       *string                `protobuf:"bytes,5,opt,name=site_url,json=siteUrl,proto3,oneof" json:"site_url,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3,oneof" json:"update_time,omitempty"`
	SubTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sub_time,json=subTime,proto3" json:"sub_time,omitempty"`
	LastPullTime  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_pull_time,json=lastPullTime,proto3" json:"last_pull_time,omitempty"`
	IsStarred     bool                   `protobuf:"varint,10,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,15,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_neon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{0}
}

func (x *Feed) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *Feed) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Feed) GetSiteUrl() string {
	if x != nil && x.SiteUrl != nil {
		return *x.SiteUrl
	}
	return ""
}

func (x *Feed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Feed) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Feed) GetSubTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubTime
	}
	return nil
}

func (x *Feed) GetLastPullTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPullTime
	}
	return nil
}

func (x *Feed) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *Feed) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FeedId        uint32                 `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsRead        bool                   `protobuf:"varint,4,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	IsBookmarked  bool                   `protobuf:"varint,5,opt,name=is_bookmarked,json=isBookmarked,proto3" json:"is_bookmarked,omitempty"`
	ExtId         string                 `protobuf:"bytes,6,opt,name=ext_id,json=extId,proto3" json:"ext_id,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	PubTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Content       *string                `protobuf:"bytes,10,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Url           *string                `protobuf:"bytes,11,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_neon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetFeedId() uint32 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *Entry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entry) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Entry) GetIsBookmarked() bool {
	if x != nil {
		return x.IsBookmarked
	}
	return false
}

func (x *Entry) GetExtId() string {
	if x != nil {
		return x.ExtId
	}
	return ""
}

func (x *Entry) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Entry) GetPubTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PubTime
	}
	return nil
}

func (x *Entry) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Entry) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Entry) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type AddFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IsStarred     *bool                  `protobuf:"varint,5,opt,name=is_starred,json=isStarred,proto3,oneof" json:"is_starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedRequest) Reset() {
	*x = AddFeedRequest{}
	mi := &file_neon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedRequest) ProtoMessage() {}

func (x *AddFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedRequest.ProtoReflect.Descriptor instead.
func (*AddFeedRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{2}
}

func (x *AddFeedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddFeedRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AddFeedRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AddFeedRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddFeedRequest) GetIsStarred() bool {
	if x != nil && x.IsStarred != nil {
		return *x.IsStarred
	}
	return false
}

type AddFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *Feed                  `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	IsAdded       bool                   `protobuf:"varint,2,opt,name=is_added,json=isAdded,proto3" json:"is_added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedResponse) Reset() {
	*x = AddFeedResponse{}
	mi := &file_neon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedResponse) ProtoMessage() {}

func (x *AddFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedResponse.ProtoReflect.Descriptor instead.
func (*AddFeedResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{3}
}

func (x *AddFeedResponse) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *AddFeedResponse) GetIsAdded() bool {
	if x != nil {
		return x.IsAdded
	}
	return false
}

type EditFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*EditFeedsRequest_Op `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFeedsRequest) Reset() {
	*x = EditFeedsRequest{}
	mi := &file_neon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFeedsRequest) ProtoMessage() {}

func (x *EditFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFeedsRequest.ProtoReflect.Descriptor instead.
func (*EditFeedsRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{4}
}

func (x *EditFeedsRequest) GetOps() []*EditFeedsRequest_Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type EditFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFeedsResponse) Reset() {
	*x = EditFeedsResponse{}
	mi := &file_neon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFeedsResponse) ProtoMessage() {}

func (x *EditFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFeedsResponse.ProtoReflect.Descriptor instead.
func (*EditFeedsResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{5}
}

func (x *EditFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type ListFeedsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxEntriesPerFeed *uint32                `protobuf:"varint,1,opt,name=max_entries_per_feed,json=maxEntriesPerFeed,proto3,oneof" json:"max_entries_per_feed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListFeedsRequest) Reset() {
	*x = ListFeedsRequest{}
	mi := &file_neon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsRequest) ProtoMessage() {}

func (x *ListFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{6}
}

func (x *ListFeedsRequest) GetMaxEntriesPerFeed() uint32 {
	if x != nil && x.MaxEntriesPerFeed != nil {
		return *x.MaxEntriesPerFeed
	}
	return 0
}

type ListFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsResponse) Reset() {
	*x = ListFeedsResponse{}
	mi := &file_neon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse) ProtoMessage() {}

func (x *ListFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{7}
}

func (x *ListFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type PullFeedsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeedIds           []uint32               `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`
	MaxEntriesPerFeed *uint32                `protobuf:"varint,2,opt,name=max_entries_per_feed,json=maxEntriesPerFeed,proto3,oneof" json:"max_entries_per_feed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullFeedsRequest) Reset() {
	*x = PullFeedsRequest{}
	mi := &file_neon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFeedsRequest) ProtoMessage() {}

func (x *PullFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFeedsRequest.ProtoReflect.Descriptor instead.
func (*PullFeedsRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{8}
}

func (x *PullFeedsRequest) GetFeedIds() []uint32 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *PullFeedsRequest) GetMaxEntriesPerFeed() uint32 {
	if x != nil && x.MaxEntriesPerFeed != nil {
		return *x.MaxEntriesPerFeed
	}
	return 0
}

type PullFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Feed          *Feed                  `protobuf:"bytes,2,opt,name=feed,proto3,oneof" json:"feed,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullFeedsResponse) Reset() {
	*x = PullFeedsResponse{}
	mi := &file_neon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFeedsResponse) ProtoMessage() {}

func (x *PullFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFeedsResponse.ProtoReflect.Descriptor instead.
func (*PullFeedsResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{9}
}

func (x *PullFeedsResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PullFeedsResponse) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *PullFeedsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeleteFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []uint32               `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedsRequest) Reset() {
	*x = DeleteFeedsRequest{}
	mi := &file_neon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedsRequest) ProtoMessage() {}

func (x *DeleteFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedsRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedsRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFeedsRequest) GetFeedIds() []uint32 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

type DeleteFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedsResponse) Reset() {
	*x = DeleteFeedsResponse{}
	mi := &file_neon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedsResponse) ProtoMessage() {}

func (x *DeleteFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedsResponse.ProtoReflect.Descriptor instead.
func (*DeleteFeedsResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{11}
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []uint32               `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`
	IsBookmarked  *bool                  `protobuf:"varint,2,opt,name=is_bookmarked,json=isBookmarked,proto3,oneof" json:"is_bookmarked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_neon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{12}
}

func (x *ListEntriesRequest) GetFeedIds() []uint32 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *ListEntriesRequest) GetIsBookmarked() bool {
	if x != nil && x.IsBookmarked != nil {
		return *x.IsBookmarked
	}
	return false
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_neon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{13}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type EditEntriesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Ops           []*EditEntriesRequest_Op `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEntriesRequest) Reset() {
	*x = EditEntriesRequest{}
	mi := &file_neon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEntriesRequest) ProtoMessage() {}

func (x *EditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEntriesRequest.ProtoReflect.Descriptor instead.
func (*EditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{14}
}

func (x *EditEntriesRequest) GetOps() []*EditEntriesRequest_Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type EditEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEntriesResponse) Reset() {
	*x = EditEntriesResponse{}
	mi := &file_neon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEntriesResponse) ProtoMessage() {}

func (x *EditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEntriesResponse.ProtoReflect.Descriptor instead.
func (*EditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{15}
}

func (x *EditEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StreamEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        uint32                 `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntriesRequest) Reset() {
	*x = StreamEntriesRequest{}
	mi := &file_neon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntriesRequest) ProtoMessage() {}

func (x *StreamEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntriesRequest.ProtoReflect.Descriptor instead.
func (*StreamEntriesRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{16}
}

func (x *StreamEntriesRequest) GetFeedId() uint32 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type StreamEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntriesResponse) Reset() {
	*x = StreamEntriesResponse{}
	mi := &file_neon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntriesResponse) ProtoMessage() {}

func (x *StreamEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntriesResponse.ProtoReflect.Descriptor instead.
func (*StreamEntriesResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEntriesResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_neon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{18}
}

func (x *GetEntryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_neon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{19}
}

func (x *GetEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ExportOPMLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOPMLRequest) Reset() {
	*x = ExportOPMLRequest{}
	mi := &file_neon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOPMLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOPMLRequest) ProtoMessage() {}

func (x *ExportOPMLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOPMLRequest.ProtoReflect.Descriptor instead.
func (*ExportOPMLRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{20}
}

func (x *ExportOPMLRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type ExportOPMLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOPMLResponse) Reset() {
	*x = ExportOPMLResponse{}
	mi := &file_neon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOPMLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOPMLResponse) ProtoMessage() {}

func (x *ExportOPMLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOPMLResponse.ProtoReflect.Descriptor instead.
func (*ExportOPMLResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{21}
}

func (x *ExportOPMLResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportOPMLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOPMLRequest) Reset() {
	*x = ImportOPMLRequest{}
	mi := &file_neon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOPMLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOPMLRequest) ProtoMessage() {}

func (x *ImportOPMLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOPMLRequest.ProtoReflect.Descriptor instead.
func (*ImportOPMLRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{22}
}

func (x *ImportOPMLRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImportOPMLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumProcessed  uint32                 `protobuf:"varint,1,opt,name=num_processed,json=numProcessed,proto3" json:"num_processed,omitempty"`
	NumImported   uint32                 `protobuf:"varint,2,opt,name=num_imported,json=numImported,proto3" json:"num_imported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOPMLResponse) Reset() {
	*x = ImportOPMLResponse{}
	mi := &file_neon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOPMLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOPMLResponse) ProtoMessage() {}

func (x *ImportOPMLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOPMLResponse.ProtoReflect.Descriptor instead.
func (*ImportOPMLResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{23}
}

func (x *ImportOPMLResponse) GetNumProcessed() uint32 {
	if x != nil {
		return x.NumProcessed
	}
	return 0
}

func (x *ImportOPMLResponse) GetNumImported() uint32 {
	if x != nil {
		return x.NumImported
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_neon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{24}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Global        *GetStatsResponse_Stats `protobuf:"bytes,1,opt,name=global,proto3,oneof" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_neon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{25}
}

func (x *GetStatsResponse) GetGlobal() *GetStatsResponse_Stats {
	if x != nil {
		return x.Global
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_neon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{26}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit     string                 `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_neon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{27}
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

type EditFeedsRequest_Op struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            uint32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        *EditFeedsRequest_Op_Fields `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFeedsRequest_Op) Reset() {
	*x = EditFeedsRequest_Op{}
	mi := &file_neon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFeedsRequest_Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFeedsRequest_Op) ProtoMessage() {}

func (x *EditFeedsRequest_Op) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFeedsRequest_Op.ProtoReflect.Descriptor instead.
func (*EditFeedsRequest_Op) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EditFeedsRequest_Op) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditFeedsRequest_Op) GetFields() *EditFeedsRequest_Op_Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EditFeedsRequest_Op_Fields struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// NOTE: This means an empty fields message in an op request will delete
	//
	//	existing tags.
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	IsStarred     *bool    `protobuf:"varint,4,opt,name=is_starred,json=isStarred,proto3,oneof" json:"is_starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditFeedsRequest_Op_Fields) Reset() {
	*x = EditFeedsRequest_Op_Fields{}
	mi := &file_neon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFeedsRequest_Op_Fields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFeedsRequest_Op_Fields) ProtoMessage() {}

func (x *EditFeedsRequest_Op_Fields) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFeedsRequest_Op_Fields.ProtoReflect.Descriptor instead.
func (*EditFeedsRequest_Op_Fields) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *EditFeedsRequest_Op_Fields) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *EditFeedsRequest_Op_Fields) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EditFeedsRequest_Op_Fields) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EditFeedsRequest_Op_Fields) GetIsStarred() bool {
	if x != nil && x.IsStarred != nil {
		return *x.IsStarred
	}
	return false
}

type EditEntriesRequest_Op struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            uint32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        *EditEntriesRequest_Op_Fields `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEntriesRequest_Op) Reset() {
	*x = EditEntriesRequest_Op{}
	mi := &file_neon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEntriesRequest_Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEntriesRequest_Op) ProtoMessage() {}

func (x *EditEntriesRequest_Op) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEntriesRequest_Op.ProtoReflect.Descriptor instead.
func (*EditEntriesRequest_Op) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{14, 0}
}

func (x *EditEntriesRequest_Op) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditEntriesRequest_Op) GetFields() *EditEntriesRequest_Op_Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EditEntriesRequest_Op_Fields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRead        *bool                  `protobuf:"varint,1,opt,name=is_read,json=isRead,proto3,oneof" json:"is_read,omitempty"`
	IsBookmarked  *bool                  `protobuf:"varint,2,opt,name=is_bookmarked,json=isBookmarked,proto3,oneof" json:"is_bookmarked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEntriesRequest_Op_Fields) Reset() {
	*x = EditEntriesRequest_Op_Fields{}
	mi := &file_neon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEntriesRequest_Op_Fields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEntriesRequest_Op_Fields) ProtoMessage() {}

func (x *EditEntriesRequest_Op_Fields) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEntriesRequest_Op_Fields.ProtoReflect.Descriptor instead.
func (*EditEntriesRequest_Op_Fields) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{14, 0, 0}
}

func (x *EditEntriesRequest_Op_Fields) GetIsRead() bool {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return false
}

func (x *EditEntriesRequest_Op_Fields) GetIsBookmarked() bool {
	if x != nil && x.IsBookmarked != nil {
		return *x.IsBookmarked
	}
	return false
}

type GetStatsResponse_Stats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NumFeeds             uint32                 `protobuf:"varint,1,opt,name=num_feeds,json=numFeeds,proto3" json:"num_feeds,omitempty"`
	NumEntries           uint32                 `protobuf:"varint,2,opt,name=num_entries,json=numEntries,proto3" json:"num_entries,omitempty"`
	NumEntriesUnread     uint32                 `protobuf:"varint,3,opt,name=num_entries_unread,json=numEntriesUnread,proto3" json:"num_entries_unread,omitempty"`
	Tag                  *string                `protobuf:"bytes,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	LastPullTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_pull_time,json=lastPullTime,proto3,oneof" json:"last_pull_time,omitempty"`
	MostRecentUpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=most_recent_update_time,json=mostRecentUpdateTime,proto3,oneof" json:"most_recent_update_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetStatsResponse_Stats) Reset() {
	*x = GetStatsResponse_Stats{}
	mi := &file_neon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse_Stats) ProtoMessage() {}

func (x *GetStatsResponse_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_neon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse_Stats.ProtoReflect.Descriptor instead.
func (*GetStatsResponse_Stats) Descriptor() ([]byte, []int) {
	return file_neon_proto_rawDescGZIP(), []int{25, 0}
}

func (x *GetStatsResponse_Stats) GetNumFeeds() uint32 {
	if x != nil {
		return x.NumFeeds
	}
	return 0
}

func (x *GetStatsResponse_Stats) GetNumEntries() uint32 {
	if x != nil {
		return x.NumEntries
	}
	return 0
}

func (x *GetStatsResponse_Stats) GetNumEntriesUnread() uint32 {
	if x != nil {
		return x.NumEntriesUnread
	}
	return 0
}

func (x *GetStatsResponse_Stats) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *GetStatsResponse_Stats) GetLastPullTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPullTime
	}
	return nil
}

func (x *GetStatsResponse_Stats) GetMostRecentUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MostRecentUpdateTime
	}
	return nil
}

var File_neon_proto protoreflect.FileDescriptor

const file_neon_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"neon.proto\x12\x04neon\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x03\n" +
	"\x04Feed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bfeed_url\x18\x03 \x01(\tR\afeedUrl\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1e\n" +
	"\bsite_url\x18\x05 \x01(\tH\x00R\asiteUrl\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x01R\vdescription\x88\x01\x01\x12@\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\n" +
	"updateTime\x88\x01\x01\x125\n" +
	"\bsub_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\asubTime\x12@\n" +
	"\x0elast_pull_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastPullTime\x12\x1d\n" +
	"\n" +
	"is_starred\x18\n" +
	" \x01(\bR\tisStarred\x12%\n" +
	"\aentries\x18\x0f \x03(\v2\v.neon.EntryR\aentriesB\v\n" +
	"\t_site_urlB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_update_time\"\x90\x03\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\rR\x06feedId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\ais_read\x18\x04 \x01(\bR\x06isRead\x12#\n" +
	"\ris_bookmarked\x18\x05 \x01(\bR\fisBookmarked\x12\x15\n" +
	"\x06ext_id\x18\x06 \x01(\tR\x05extId\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x125\n" +
	"\bpub_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\apubTime\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\n" +
	" \x01(\tH\x01R\acontent\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\v \x01(\tH\x02R\x03url\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_contentB\x06\n" +
	"\x04_url\"\xc5\x01\n" +
	"\x0eAddFeedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\"\n" +
	"\n" +
	"is_starred\x18\x05 \x01(\bH\x02R\tisStarred\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_starred\"L\n" +
	"\x0fAddFeedResponse\x12\x1e\n" +
	"\x04feed\x18\x01 \x01(\v2\n" +
	".neon.FeedR\x04feed\x12\x19\n" +
	"\bis_added\x18\x02 \x01(\bR\aisAdded\"\xbe\x02\n" +
	"\x10EditFeedsRequest\x12+\n" +
	"\x03ops\x18\x01 \x03(\v2\x19.neon.EditFeedsRequest.OpR\x03ops\x1a\xfc\x01\n" +
	"\x02Op\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x128\n" +
	"\x06fields\x18\x02 \x01(\v2 .neon.EditFeedsRequest.Op.FieldsR\x06fields\x1a\xab\x01\n" +
	"\x06Fields\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\"\n" +
	"\n" +
	"is_starred\x18\x04 \x01(\bH\x02R\tisStarred\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_starred\"5\n" +
	"\x11EditFeedsResponse\x12 \n" +
	"\x05feeds\x18\x01 \x03(\v2\n" +
	".neon.FeedR\x05feeds\"a\n" +
	"\x10ListFeedsRequest\x124\n" +
	"\x14max_entries_per_feed\x18\x01 \x01(\rH\x00R\x11maxEntriesPerFeed\x88\x01\x01B\x17\n" +
	"\x15_max_entries_per_feed\"5\n" +
	"\x11ListFeedsResponse\x12 \n" +
	"\x05feeds\x18\x01 \x03(\v2\n" +
	".neon.FeedR\x05feeds\"|\n" +
	"\x10PullFeedsRequest\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\rR\afeedIds\x124\n" +
	"\x14max_entries_per_feed\x18\x02 \x01(\rH\x00R\x11maxEntriesPerFeed\x88\x01\x01B\x17\n" +
	"\x15_max_entries_per_feed\"x\n" +
	"\x11PullFeedsResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12#\n" +
	"\x04feed\x18\x02 \x01(\v2\n" +
	".neon.FeedH\x00R\x04feed\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_feedB\b\n" +
	"\x06_error\"/\n" +
	"\x12DeleteFeedsRequest\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\rR\afeedIds\"\x15\n" +
	"\x13DeleteFeedsResponse\"k\n" +
	"\x12ListEntriesRequest\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\rR\afeedIds\x12(\n" +
	"\ris_bookmarked\x18\x02 \x01(\bH\x00R\fisBookmarked\x88\x01\x01B\x10\n" +
	"\x0e_is_bookmarked\"<\n" +
	"\x13ListEntriesResponse\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.neon.EntryR\aentries\"\x86\x02\n" +
	"\x12EditEntriesRequest\x12-\n" +
	"\x03ops\x18\x01 \x03(\v2\x1b.neon.EditEntriesRequest.OpR\x03ops\x1a\xc0\x01\n" +
	"\x02Op\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12:\n" +
	"\x06fields\x18\x02 \x01(\v2\".neon.EditEntriesRequest.Op.FieldsR\x06fields\x1an\n" +
	"\x06Fields\x12\x1c\n" +
	"\ais_read\x18\x01 \x01(\bH\x00R\x06isRead\x88\x01\x01\x12(\n" +
	"\ris_bookmarked\x18\x02 \x01(\bH\x01R\fisBookmarked\x88\x01\x01B\n" +
	"\n" +
	"\b_is_readB\x10\n" +
	"\x0e_is_bookmarked\"<\n" +
	"\x13EditEntriesResponse\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.neon.EntryR\aentries\"/\n" +
	"\x14StreamEntriesRequest\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\rR\x06feedId\":\n" +
	"\x15StreamEntriesResponse\x12!\n" +
	"\x05entry\x18\x01 \x01(\v2\v.neon.EntryR\x05entry\"!\n" +
	"\x0fGetEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"5\n" +
	"\x10GetEntryResponse\x12!\n" +
	"\x05entry\x18\x01 \x01(\v2\v.neon.EntryR\x05entry\"8\n" +
	"\x11ExportOPMLRequest\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title\".\n" +
	"\x12ExportOPMLResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"-\n" +
	"\x11ImportOPMLRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\\\n" +
	"\x12ImportOPMLResponse\x12#\n" +
	"\rnum_processed\x18\x01 \x01(\rR\fnumProcessed\x12!\n" +
	"\fnum_imported\x18\x02 \x01(\rR\vnumImported\"\x11\n" +
	"\x0fGetStatsRequest\"\xbb\x03\n" +
	"\x10GetStatsResponse\x129\n" +
	"\x06global\x18\x01 \x01(\v2\x1c.neon.GetStatsResponse.StatsH\x00R\x06global\x88\x01\x01\x1a\xe0\x02\n" +
	"\x05Stats\x12\x1b\n" +
	"\tnum_feeds\x18\x01 \x01(\rR\bnumFeeds\x12\x1f\n" +
	"\vnum_entries\x18\x02 \x01(\rR\n" +
	"numEntries\x12,\n" +
	"\x12num_entries_unread\x18\x03 \x01(\rR\x10numEntriesUnread\x12\x15\n" +
	"\x03tag\x18\x04 \x01(\tH\x00R\x03tag\x88\x01\x01\x12E\n" +
	"\x0elast_pull_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\flastPullTime\x88\x01\x01\x12V\n" +
	"\x17most_recent_update_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x14mostRecentUpdateTime\x88\x01\x01B\x06\n" +
	"\x04_tagB\x11\n" +
	"\x0f_last_pull_timeB\x1a\n" +
	"\x18_most_recent_update_timeB\t\n" +
	"\a_global\"\x10\n" +
	"\x0eGetInfoRequest\"^\n" +
	"\x0fGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x03 \x01(\tR\tgitCommit2\xdc\x06\n" +
	"\x04Neon\x128\n" +
	"\aAddFeed\x12\x14.neon.AddFeedRequest\x1a\x15.neon.AddFeedResponse\"\x00\x12>\n" +
	"\tEditFeeds\x12\x16.neon.EditFeedsRequest\x1a\x17.neon.EditFeedsResponse\"\x00\x12>\n" +
	"\tListFeeds\x12\x16.neon.ListFeedsRequest\x1a\x17.neon.ListFeedsResponse\"\x00\x12@\n" +
	"\tPullFeeds\x12\x16.neon.PullFeedsRequest\x1a\x17.neon.PullFeedsResponse\"\x000\x01\x12D\n" +
	"\vDeleteFeeds\x12\x18.neon.DeleteFeedsRequest\x1a\x19.neon.DeleteFeedsResponse\"\x00\x12L\n" +
	"\rStreamEntries\x12\x1a.neon.StreamEntriesRequest\x1a\x1b.neon.StreamEntriesResponse\"\x000\x01\x12D\n" +
	"\vListEntries\x12\x18.neon.ListEntriesRequest\x1a\x19.neon.ListEntriesResponse\"\x00\x12D\n" +
	"\vEditEntries\x12\x18.neon.EditEntriesRequest\x1a\x19.neon.EditEntriesResponse\"\x00\x12;\n" +
	"\bGetEntry\x12\x15.neon.GetEntryRequest\x1a\x16.neon.GetEntryResponse\"\x00\x12A\n" +
	"\n" +
	"ExportOPML\x12\x17.neon.ExportOPMLRequest\x1a\x18.neon.ExportOPMLResponse\"\x00\x12A\n" +
	"\n" +
	"ImportOPML\x12\x17.neon.ImportOPMLRequest\x1a\x18.neon.ImportOPMLResponse\"\x00\x12;\n" +
	"\bGetStats\x12\x15.neon.GetStatsRequest\x1a\x16.neon.GetStatsResponse\"\x00\x128\n" +
	"\aGetInfo\x12\x14.neon.GetInfoRequest\x1a\x15.neon.GetInfoResponse\"\x00B\x19Z\x17github.com/bow/neon/apib\x06proto3"

var (
	file_neon_proto_rawDescOnce sync.Once
	file_neon_proto_rawDescData []byte
)

func file_neon_proto_rawDescGZIP() []byte {
	file_neon_proto_rawDescOnce.Do(func() {
		file_neon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neon_proto_rawDesc), len(file_neon_proto_rawDesc)))
	})
	return file_neon_proto_rawDescData
}

var file_neon_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_neon_proto_goTypes = []any{
	(*Feed)(nil),                         // 0: neon.Feed
	(*Entry)(nil),                        // 1: neon.Entry
	(*AddFeedRequest)(nil),               // 2: neon.AddFeedRequest
	(*AddFeedResponse)(nil),              // 3: neon.AddFeedResponse
	(*EditFeedsRequest)(nil),             // 4: neon.EditFeedsRequest
	(*EditFeedsResponse)(nil),            // 5: neon.EditFeedsResponse
	(*ListFeedsRequest)(nil),             // 6: neon.ListFeedsRequest
	(*ListFeedsResponse)(nil),            // 7: neon.ListFeedsResponse
	(*PullFeedsRequest)(nil),             // 8: neon.PullFeedsRequest
	(*PullFeedsResponse)(nil),            // 9: neon.PullFeedsResponse
	(*DeleteFeedsRequest)(nil),           // 10: neon.DeleteFeedsRequest
	(*DeleteFeedsResponse)(nil),          // 11: neon.DeleteFeedsResponse
	(*ListEntriesRequest)(nil),           // 12: neon.ListEntriesRequest
	(*ListEntriesResponse)(nil),          // 13: neon.ListEntriesResponse
	(*EditEntriesRequest)(nil),           // 14: neon.EditEntriesRequest
	(*EditEntriesResponse)(nil),          // 15: neon.EditEntriesResponse
	(*StreamEntriesRequest)(nil),         // 16: neon.StreamEntriesRequest
	(*StreamEntriesResponse)(nil),        // 17: neon.StreamEntriesResponse
	(*GetEntryRequest)(nil),              // 18: neon.GetEntryRequest
	(*GetEntryResponse)(nil),             // 19: neon.GetEntryResponse
	(*ExportOPMLRequest)(nil),            // 20: neon.ExportOPMLRequest
	(*ExportOPMLResponse)(nil),           // 21: neon.ExportOPMLResponse
	(*ImportOPMLRequest)(nil),            // 22: neon.ImportOPMLRequest
	(*ImportOPMLResponse)(nil),           // 23: neon.ImportOPMLResponse
	(*GetStatsRequest)(nil),              // 24: neon.GetStatsRequest
	(*GetStatsResponse)(nil),             // 25: neon.GetStatsResponse
	(*GetInfoRequest)(nil),               // 26: neon.GetInfoRequest
	(*GetInfoResponse)(nil),              // 27: neon.GetInfoResponse
	(*EditFeedsRequest_Op)(nil),          // 28: neon.EditFeedsRequest.Op
	(*EditFeedsRequest_Op_Fields)(nil),   // 29: neon.EditFeedsRequest.Op.Fields
	(*EditEntriesRequest_Op)(nil),        // 30: neon.EditEntriesRequest.Op
	(*EditEntriesRequest_Op_Fields)(nil), // 31: neon.EditEntriesRequest.Op.Fields
	(*GetStatsResponse_Stats)(nil),       // 32: neon.GetStatsResponse.Stats
	(*timestamppb.Timestamp)(nil),        // 33: google.protobuf.Timestamp
}
var file_neon_proto_depIdxs = []int32{
	33, // 0: neon.Feed.update_time:type_name -> google.protobuf.Timestamp
	33, // 1: neon.Feed.sub_time:type_name -> google.protobuf.Timestamp
	33, // 2: neon.Feed.last_pull_time:type_name -> google.protobuf.Timestamp
	1,  // 3: neon.Feed.entries:type_name -> neon.Entry
	33, // 4: neon.Entry.update_time:type_name -> google.protobuf.Timestamp
	33, // 5: neon.Entry.pub_time:type_name -> google.protobuf.Timestamp
	0,  // 6: neon.AddFeedResponse.feed:type_name -> neon.Feed
	28, // 7: neon.EditFeedsRequest.ops:type_name -> neon.EditFeedsRequest.Op
	0,  // 8: neon.EditFeedsResponse.feeds:type_name -> neon.Feed
	0,  // 9: neon.ListFeedsResponse.feeds:type_name -> neon.Feed
	0,  // 10: neon.PullFeedsResponse.feed:type_name -> neon.Feed
	1,  // 11: neon.ListEntriesResponse.entries:type_name -> neon.Entry
	30, // 12: neon.EditEntriesRequest.ops:type_name -> neon.EditEntriesRequest.Op
	1,  // 13: neon.EditEntriesResponse.entries:type_name -> neon.Entry
	1,  // 14: neon.StreamEntriesResponse.entry:type_name -> neon.Entry
	1,  // 15: neon.GetEntryResponse.entry:type_name -> neon.Entry
	32, // 16: neon.GetStatsResponse.global:type_name -> neon.GetStatsResponse.Stats
	29, // 17: neon.EditFeedsRequest.Op.fields:type_name -> neon.EditFeedsRequest.Op.Fields
	31, // 18: neon.EditEntriesRequest.Op.fields:type_name -> neon.EditEntriesRequest.Op.Fields
	33, // 19: neon.GetStatsResponse.Stats.last_pull_time:type_name -> google.protobuf.Timestamp
	33, // 20: neon.GetStatsResponse.Stats.most_recent_update_time:type_name -> google.protobuf.Timestamp
	2,  // 21: neon.Neon.AddFeed:input_type -> neon.AddFeedRequest
	4,  // 22: neon.Neon.EditFeeds:input_type -> neon.EditFeedsRequest
	6,  // 23: neon.Neon.ListFeeds:input_type -> neon.ListFeedsRequest
	8,  // 24: neon.Neon.PullFeeds:input_type -> neon.PullFeedsRequest
	10, // 25: neon.Neon.DeleteFeeds:input_type -> neon.DeleteFeedsRequest
	16, // 26: neon.Neon.StreamEntries:input_type -> neon.StreamEntriesRequest
	12, // 27: neon.Neon.ListEntries:input_type -> neon.ListEntriesRequest
	14, // 28: neon.Neon.EditEntries:input_type -> neon.EditEntriesRequest
	18, // 29: neon.Neon.GetEntry:input_type -> neon.GetEntryRequest
	20, // 30: neon.Neon.ExportOPML:input_type -> neon.ExportOPMLRequest
	22, // 31: neon.Neon.ImportOPML:input_type -> neon.ImportOPMLRequest
	24, // 32: neon.Neon.GetStats:input_type -> neon.GetStatsRequest
	26, // 33: neon.Neon.GetInfo:input_type -> neon.GetInfoRequest
	3,  // 34: neon.Neon.AddFeed:output_type -> neon.AddFeedResponse
	5,  // 35: neon.Neon.EditFeeds:output_type -> neon.EditFeedsResponse
	7,  // 36: neon.Neon.ListFeeds:output_type -> neon.ListFeedsResponse
	9,  // 37: neon.Neon.PullFeeds:output_type -> neon.PullFeedsResponse
	11, // 38: neon.Neon.DeleteFeeds:output_type -> neon.DeleteFeedsResponse
	17, // 39: neon.Neon.StreamEntries:output_type -> neon.StreamEntriesResponse
	13, // 40: neon.Neon.ListEntries:output_type -> neon.ListEntriesResponse
	15, // 41: neon.Neon.EditEntries:output_type -> neon.EditEntriesResponse
	19, // 42: neon.Neon.GetEntry:output_type -> neon.GetEntryResponse
	21, // 43: neon.Neon.ExportOPML:output_type -> neon.ExportOPMLResponse
	23, // 44: neon.Neon.ImportOPML:output_type -> neon.ImportOPMLResponse
	25, // 45: neon.Neon.GetStats:output_type -> neon.GetStatsResponse
	27, // 46: neon.Neon.GetInfo:output_type -> neon.GetInfoResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_neon_proto_init() }
func file_neon_proto_init() {
	if File_neon_proto != nil {
		return
	}
	file_neon_proto_msgTypes[0].OneofWrappers = []any{}
	file_neon_proto_msgTypes[1].OneofWrappers = []any{}
	file_neon_proto_msgTypes[2].OneofWrappers = []any{}
	file_neon_proto_msgTypes[6].OneofWrappers = []any{}
	file_neon_proto_msgTypes[8].OneofWrappers = []any{}
	file_neon_proto_msgTypes[9].OneofWrappers = []any{}
	file_neon_proto_msgTypes[12].OneofWrappers = []any{}
	file_neon_proto_msgTypes[20].OneofWrappers = []any{}
	file_neon_proto_msgTypes[25].OneofWrappers = []any{}
	file_neon_proto_msgTypes[29].OneofWrappers = []any{}
	file_neon_proto_msgTypes[31].OneofWrappers = []any{}
	file_neon_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neon_proto_rawDesc), len(file_neon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neon_proto_goTypes,
		DependencyIndexes: file_neon_proto_depIdxs,
		MessageInfos:      file_neon_proto_msgTypes,
	}.Build()
	File_neon_proto = out.File
	file_neon_proto_goTypes = nil
	file_neon_proto_depIdxs = nil
}
